### PR TITLE
feat: jim and brians code

### PR DESCRIPTION
**Pull request by ptbw**

### CODE REVIEW

**Comment by hackerjimbo** [comment]
This is a good _start_, but we're going to need to factorise out the device dependant stuff and make it a lot clearer and cleaner for the small people.

**Comment by Godley** [comment]
Please provide specifics, like going through the code and commenting on which bits you'd like moving - as far as I'm concerned I've abstracted it as much as I'd like, though I might change test_motor_code to follow the same pattern as base_robot_code.

**Comment by ptbw** [comment]
Looks pretty good to me. I will cut you a board to mount stuff on and a camera bracket for a pi camera. There sample over the rainbow code here: https://piwars.org/2018-competition/challenges/somewhere-over-the-rainbow/over-the-rainbow-sample-code/

**Comment by ptbw** [comment]
Closed by mistake

**Comment by Godley** [comment]
Gah, can't really test this because I have no wifi chip. I'll order one then check this out with my cam jam kit. As it stands probably just going to merge it then submit fixes if there are any

**Pull request merged**
